apiVersion: v1
kind: Service
metadata:
  name: cowweb
  labels:
    app: cowweb
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 400Mbps
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: cowweb
  type: LoadBalancer
