apiVersion: v1
kind: Service
metadata:
  name: cowweb
  labels:
    app: cowweb
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: cowweb
  type: LoadBalancer
